version: '3.8'

services:
  app:
    container_name: spring-boot-app
    image: ${DOCKER_IMAGE} 
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_ACCESS: ${JWT_EXPIRATION_ACCESS}
      JWT_EXPIRATION_REFRESH: ${JWT_EXPIRATION_REFRESH}
